### ISSUE TITLE
task #2 clase Conexion

### ISSUE THREAD

**Issue by JuanPa-Portugal** [CodeSystem2022/integrador_CodeStyle_Centronutricional_2023#2]
crear rama local con apellido e iniciales de su nombre

Dentro la carpeta CentroNutricional:

- [x] crear el archivo conexion.py
- [x] realizar las importaciones psycopg2
- [x] importar log desde logger_base
- [x] import Sys
- [x] crear Clase Conexion
- [x] crear metodos 
   - obtenerConexion
   - obtenerCursor

**Comment by gabi-silva** [comment]
Terminada mi tarea
