### ISSUE TITLE
task #4  Clase PacienteDAO

### ISSUE THREAD

**Issue by JuanPa-Portugal** [CodeSystem2022/integrador_CodeStyle_Centronutricional_2023#4]
crear rama local con apellido e iniciales de su nombre

Dentro la carpeta CentroNutricional:

- [x] Crear el archivo PacienteDAO.py
- [x] realizar las importaciones Paciente, conexion, log
- [x] crear Clase PacienteDAO
- [x] realizar las querys SELECT, INSERT, UPDATE, DELETE, SELECT_PACIENTE, SELECT_PACIENTES_ELIMINADOS
- [x] definir los metodos 
    - seleccionar
    - seleccionarPaciente
    - insertar

**Comment by ivanagermir** [comment]
Tarea completada
